spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  application:
    name: Vanilla
security:
    user:
      password: password
    oauth2:
      resource:
        filter-order: 3